# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170211_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='path',
            field=models.SlugField(max_length=80, unique=True),
        ),
    ]
